language: 
  - python
before-install:
 # - python manage.py migrate
  - pip install -r requirements.txt
 # - pip install flake8
  - pip install black
  - pip install coverage
  - pip install coveralls
script:
  - python manage.py
  - black --check .
  - flake8 .
after_success:
  - coveralls