language: python
script: python manage.py
language:
  - python
before-install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install black
  - pip install coverage
  - pip install coveralls
script:
  - black --check .
  - flake8 --max-line-length=88 .
#  - coverage run --source=home manage.py test home
after_success:
  - coveralls